version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mail-dispatch-service
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - backend

  db:
    image: postgres:16-alpine
    container_name: db-postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - backend

  celery:
    build: .
    command: ["/bin/bash", "/code/wait-for-services.sh", "celery", "-A", "my_project", "worker", "--loglevel=info"]
    depends_on:
      - redis
      - web
    env_file:
      - .env
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge