version: '3.9'

services:
  # Контейнер с приложением
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newsletter_service
    volumes:
      - .:/newsletter_service
    env_file:
      - ./.env  # Подключаем файл с переменными окружения
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - backend

  # Контейнер с базой данных PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: db-postgres-platform_bestcar
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  # Контейнер Redis
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge