# Generated by Django 5.1.6 on 2025-02-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('message_text', models.TextField(verbose_name='Message Text')),
                ('operator_code_filter', models.CharField(max_length=3, verbose_name='Operator Code')),
                ('tag_filter', models.CharField(max_length=255, verbose_name='Tag')),
            ],
        ),
    ]
