# Generated by Django 5.1.6 on 2025-02-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='end_time',
            field=models.DateTimeField(verbose_name='Дата и время окончания'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='message_text',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='operator_code_filter',
            field=models.CharField(max_length=3, verbose_name='Код оператора'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_time',
            field=models.DateTimeField(verbose_name='Дата и время начала'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='tag_filter',
            field=models.CharField(max_length=255, verbose_name='Тег'),
        ),
    ]
