# Generated by Django 5.1.6 on 2025-02-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_end_time_alter_campaign_message_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
