# Generated by Django 5.1.6 on 2025-02-20 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_end_time_alter_campaign_message_text_and_more'),
        ('client', '0003_alter_client_operator_code_alter_client_phone_number_and_more'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='campaigns.campaign', verbose_name='Кампания'),
        ),
        migrations.AlterField(
            model_name='message',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='client.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Отправлено в'),
        ),
    ]
