# Generated by Django 5.1.6 on 2025-02-20 17:13

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', unique=True, verbose_name='Phone number')),
                ('operator_code', models.CharField(max_length=3, verbose_name='Operator code')),
                ('tag', models.CharField(blank=True, max_length=255, null=True, verbose_name='Client tag')),
            ],
        ),
    ]
