# Generated by Django 5.1.6 on 2025-02-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='operator_code',
            field=models.CharField(blank=True, max_length=3, verbose_name='Operator code'),
        ),
    ]
